# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll for Web Designers
#email: your-email@domain.com
description: "This is my 3rd attempt to finally learn Jekyll. I've been told that it is a powerful tool and I believe it!"
baseurl: "/jekyll-for-designers" # the subpath of your site, e.g. /blog
url: "http://adamgonzls.github.io/jekyll-for-designers" # the base hostname & protocol for your site
twitter_username: adamgonzls
github_username:  adamgonzls
tagline: "A basic guide to Jekyll"

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
gems: [jekyll-paginate]
paginate: 3
paginate_path: '/blog/page:num/'
permalink: /blog/:title